apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.queryFrontEnd.clusterRoleBindingName }}
  namespace: {{ .Values.monitoring.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ .Values.queryFrontEnd.serviceAccountName }}
    namespace: {{ .Values.monitoring.namespace }}