apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-rbac-proxy
  namespace: {{ .Values.monitoring.namespace }}
data:
  config.yaml: |+
    authorization:
      rewrites:
        byQueryParameter:
          name: "namespace"
      resourceAttributes:
        apiVersion: v1
        resource: pods
        subresource: metrics
        namespace: "{{ printf "{{ .Value }}" }}"