apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-frontend
  namespace: {{ .Values.monitoring.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "monitoring.queryFrontEnd" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "monitoring.queryFrontEnd" . | nindent 8 }}
        type: querier-frontend
    spec:
      serviceAccountName: {{ .Values.queryFrontEnd.serviceAccountName }}
      containers:
        - name: kube-rbac-proxy
          image: quay.io/brancz/kube-rbac-proxy:v0.18.1
          args:
            - "--secure-listen-address=0.0.0.0:9090"
            - "--upstream=http://127.0.0.1:8080/"
            - "--config-file=/etc/kube-rbac-proxy/config.yaml"
            - "--logtostderr=true"
            - "--v=10"
          ports:
            - containerPort: 9090
              name: https
          volumeMounts:
            - name: config
              mountPath: /etc/kube-rbac-proxy
          resources:
            {{- toYaml .Values.queryFrontEnd.rbacProxy.resources | nindent 12 }}
        - name: prom-label-proxy
          image: quay.io/prometheuscommunity/prom-label-proxy:v0.11.0
          imagePullPolicy: Always
          args:
            - "--insecure-listen-address=127.0.0.1:8080"
            - "--upstream=http://{{ .Values.monitoring.prometheusService }}.{{ .Values.monitoring.namespace }}.svc.cluster.local:{{ .Values.monitoring.port }}/"
            - "--label=namespace"
            - "--enable-label-apis=true"
          resources:
            {{- toYaml  .Values.queryFrontEnd.proxLabelProxy.resources | nindent 12 }}
          ports:
            - containerPort: 8080
              name: https
      volumes:
        - name: config
          configMap:
            name: kube-rbac-proxy