apiVersion: v1
kind: Service
metadata:
  name: prom-frontend
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    {{- include "monitoring.queryFrontEnd" . | nindent 4}}
spec:
  selector:
    {{- include "monitoring.queryFrontEnd" . | nindent 6}}
  ports:
    - name: http
      port: 9090
      targetPort: 9090