apiVersion: v1
kind: Service
metadata:
  name: thanos-querier-frontend
  namespace: monitoring
  labels:
    app: prom-frontend
spec:
  selector:
    app: prom-frontend
  ports:
    - name: http
      port: 9090
      targetPort: 9090