---
# Source: monitoring/templates/querier-frontend/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-kube-rbac-proxy
  namespace: monitoring
---
# Source: monitoring/templates/tenant/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant1-grafana-sa
  namespace: tenant1-ns
---
# Source: monitoring/templates/tenant/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant2-grafana-sa
  namespace: tenant2-ns
---
# Source: monitoring/templates/tenant/token.yaml
apiVersion: v1
kind: Secret
metadata:
  name: tenant1-grafana-sa-token
  namespace: tenant1-ns
  annotations:
    kubernetes.io/service-account.name: tenant1-grafana-sa
type: kubernetes.io/service-account-token
---
# Source: monitoring/templates/tenant/token.yaml
apiVersion: v1
kind: Secret
metadata:
  name: tenant2-grafana-sa-token
  namespace: tenant2-ns
  annotations:
    kubernetes.io/service-account.name: tenant2-grafana-sa
type: kubernetes.io/service-account-token
---
# Source: monitoring/templates/querier-frontend/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-rbac-proxy
  namespace: monitoring
data:
  config.yaml: |+
    authorization:
      rewrites:
        byQueryParameter:
          name: "namespace"
      resourceAttributes:
        apiVersion: v1
        resource: pods
        subresource: metrics
        namespace: ""
---
# Source: monitoring/templates/tenant/grafana.yaml
# ConfigMap to hold the datasource configuration for tenant1
apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant1-grafana-datasource-config
  namespace: tenant1-ns
  labels:
    grafana_datasource: "1"
data:
  # https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-configuration-file
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: tenant1-prometheus
        access: proxy
        url: https://prom-frontend.monitoring.svc.cluster.local:9090/
        isDefault: true
        editable: false
        jsonData:
          # This is the key for tenant isolation
          customQueryParameters: "namespace=tenant1-ns"
          httpHeaderName1: "Authorization"
          httpMethod: "GET"
          queryTimeout: 5m
          timeInterval: 30s
          tlsSkipVerify: true
        secureJsonData:
          httpHeaderValue1: "Bearer ${PROMETHEUS_TOKEN}"
---
# Source: monitoring/templates/tenant/grafana.yaml
# ConfigMap to hold the datasource configuration for tenant2
apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant2-grafana-datasource-config
  namespace: tenant2-ns
  labels:
    grafana_datasource: "1"
data:
  # https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-configuration-file
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: tenant2-prometheus
        access: proxy
        url: https://prom-frontend.monitoring.svc.cluster.local:9090/
        isDefault: true
        editable: false
        jsonData:
          # This is the key for tenant isolation
          customQueryParameters: "namespace=tenant2-ns"
          httpHeaderName1: "Authorization"
          httpMethod: "GET"
          queryTimeout: 5m
          timeInterval: 30s
          tlsSkipVerify: true
        secureJsonData:
          httpHeaderValue1: "Bearer ${PROMETHEUS_TOKEN}"
---
# Source: monitoring/templates/querier-frontend/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-kube-rbac-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: prometheus-kube-rbac-proxy
    namespace: monitoring
---
# Source: monitoring/templates/tenant/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant1-grafana-role
  namespace: tenant1-ns
rules:
  - apiGroups: [""]
    resources:
      - pods/metrics
    verbs: ["get"]
---
# Source: monitoring/templates/tenant/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant2-grafana-role
  namespace: tenant2-ns
rules:
  - apiGroups: [""]
    resources:
      - pods/metrics
    verbs: ["get"]
---
# Source: monitoring/templates/tenant/service-account.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant1-grafana-rb
  namespace: tenant1-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant1-grafana-role
subjects:
  - kind: ServiceAccount
    name: tenant1-grafana-sa
    namespace: tenant1-ns
---
# Source: monitoring/templates/tenant/service-account.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant2-grafana-rb
  namespace: tenant2-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant2-grafana-role
subjects:
  - kind: ServiceAccount
    name: tenant2-grafana-sa
    namespace: tenant2-ns
---
# Source: monitoring/templates/querier-frontend/proxy.yaml
apiVersion: v1
kind: Service
metadata:
  name: prom-frontend
  namespace: monitoring
  labels:
    app: prom-frontend
spec:
  selector:
      app: prom-frontend
  ports:
    - name: http
      port: 9090
      targetPort: 9090
---
# Source: monitoring/templates/tenant/grafana.yaml
# Service to expose the Grafana instance for tenant1
apiVersion: v1
kind: Service
metadata:
  name: tenant1-grafana-svc
  namespace: tenant1-ns
spec:
  selector:
    app: grafana
    tenant: tenant1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: http
---
# Source: monitoring/templates/tenant/grafana.yaml
# Service to expose the Grafana instance for tenant2
apiVersion: v1
kind: Service
metadata:
  name: tenant2-grafana-svc
  namespace: tenant2-ns
spec:
  selector:
    app: grafana
    tenant: tenant2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: http
---
# Source: monitoring/templates/querier-frontend/proxy-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-frontend
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-frontend
  template:
    metadata:
      labels:
        app: prom-frontend
        type: querier-frontend
    spec:
      serviceAccountName: prometheus-kube-rbac-proxy
      containers:
        - name: kube-rbac-proxy
          image: quay.io/brancz/kube-rbac-proxy:v0.18.1
          args:
            - "--secure-listen-address=0.0.0.0:9090"
            - "--upstream=http://127.0.0.1:8080/"
            - "--config-file=/etc/kube-rbac-proxy/config.yaml"
            - "--logtostderr=true"
            - "--v=10"
          ports:
            - containerPort: 9090
              name: https
          volumeMounts:
            - name: config
              mountPath: /etc/kube-rbac-proxy
          resources:
            limits:
              cpu: 150m
              memory: 500Mi
            requests:
              cpu: 30m
              memory: 64Mi
        - name: prom-label-proxy
          image: quay.io/prometheuscommunity/prom-label-proxy:v0.11.0
          imagePullPolicy: Always
          args:
            - "--insecure-listen-address=127.0.0.1:8080"
            - "--upstream=http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/"
            - "--label=namespace"
            - "--enable-label-apis=true"
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 30m
              memory: 64Mi
          ports:
            - containerPort: 8080
              name: https
      volumes:
        - name: config
          configMap:
            name: kube-rbac-proxy
---
# Source: monitoring/templates/tenant/grafana.yaml
# Grafana Deployment for tenant1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant1-grafana
  namespace: tenant1-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      tenant: tenant1
  template:
    metadata:
      labels:
        app: grafana
        tenant: tenant1
    spec:
      serviceAccountName: tenant1-grafana-sa
      containers:
        - name: grafana
          image: grafana/grafana:12.0.2 # Use a specific Grafana version
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 64m
              memory: 64Mi
          env:
            - name: PROMETHEUS_TOKEN
              valueFrom:
                secretKeyRef:
                  # Assumes a secret with this name and key exists for the tenant
                  name: tenant1-grafana-sa-token
                  key: token
          volumeMounts:
            - name: datasource-config
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: datasource-config
          configMap:
            name: tenant1-grafana-datasource-config
---
# Source: monitoring/templates/tenant/grafana.yaml
# Grafana Deployment for tenant2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant2-grafana
  namespace: tenant2-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      tenant: tenant2
  template:
    metadata:
      labels:
        app: grafana
        tenant: tenant2
    spec:
      serviceAccountName: tenant2-grafana-sa
      containers:
        - name: grafana
          image: grafana/grafana:12.0.2 # Use a specific Grafana version
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 64m
              memory: 64Mi
          env:
            - name: PROMETHEUS_TOKEN
              valueFrom:
                secretKeyRef:
                  # Assumes a secret with this name and key exists for the tenant
                  name: tenant2-grafana-sa-token
                  key: token
          volumeMounts:
            - name: datasource-config
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: datasource-config
          configMap:
            name: tenant2-grafana-datasource-config
