{{- range .Values.tenants }}
---
# ConfigMap to hold the datasource configuration for {{ .name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-grafana-datasource-config
  namespace: {{ .namespace }}
  labels:
    grafana_datasource: "1"
data:
  # https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-configuration-file
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: {{ .name }}-prometheus
        access: proxy
        url: https://prom-frontend.{{ $.Values.monitoring.namespace }}.svc.cluster.local:9090/
        isDefault: true
        editable: false
        jsonData:
          # This is the key for tenant isolation
          customQueryParameters: "namespace={{ .namespace }}"
          httpHeaderName1: "Authorization"
          httpMethod: "GET"
          queryTimeout: 5m
          timeInterval: 30s
          tlsSkipVerify: true
        secureJsonData:
          httpHeaderValue1: "Bearer ${PROMETHEUS_TOKEN}"

{{- end }}