{{- range .Values.tenants }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .name }}-grafana-role
  namespace: {{ .namespace }}
rules:
  - apiGroups: [""]
    resources:
      - pods/metrics
    verbs: ["get"]
{{- end }}