tenants:
  - name: tenant1
    namespace: tenant1-ns
  - name: tenant2
    namespace: tenant2-ns

monitoring:
  namespace: monitoring
  prometheusService: prometheus-kube-prometheus-prometheus
  port: 9090
  grafana:
    version: 12.0.2
    resource: # probably do it separately, we might need separate resource requests for separate tenants
      requests:
        cpu: "64m"
        memory: "64Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"
queryFrontEnd:
  serviceAccountName: prometheus-kube-rbac-proxy
  clusterRoleBindingName: prometheus-kube-rbac-proxy
  rbacProxy:
    resources:
      requests:
        memory: 64Mi
        cpu: 30m
      limits:
        memory: 500Mi
        cpu: 150m
  proxLabelProxy:
    resources:
      requests:
        memory: 64Mi
        cpu: 30m
      limits:
        memory: 500Mi
        cpu: 100m