apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: tenant-1-ns
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus-app
  namespaceSelector:
    any: true
  endpoints:
    - port: web