---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-1
  namespace: tenant-1-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-1-metrics-viewer
  namespace: tenant-1-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  # Role or ClusterRole here, depending on which you chose to provision
  kind: Role
  name: namespace-metrics-viewer
subjects:
  - kind: ServiceAccount
    name: tenant-1
    namespace: tenant-1-ns